syntax = { rule+ ~ EOI }

rule = { 
	opt_whitespace 
	~ rule_name
	~ opt_whitespace
	~ "::="
	~ opt_whitespace
	~ expression 
	~ line_end
}

expression = {
	sequence ~ (
		or
		~ sequence
	)* 

}

or = { "|" } 

sequence = { item+ }
item = { 
	opt_whitespace ~ (optional | repetition | literal | rule_name) ~ opt_whitespace

}


repetition = {
	"{" ~ opt_whitespace ~ expression ~ opt_whitespace ~ "}"
}

optional = {
	"[" ~ opt_whitespace ~ expression ~ opt_whitespace ~ "]"
}


list = { 
	term ~ opt_whitespace ~ list | 
	term 
} 

term = { (literal | rule_name )} 



literal = {
	"\"" ~ text1 ~ "\"" | 
	"'" ~ text2 ~ "'"
}

text1 = { (character1 ~ text1)* }
text2 = { (character2 ~ text2)*}


letter = { ASCII_ALPHA }
digit = { ASCII_DIGIT }
symbol = {
    "|" | " "  | "!" | "#" | "$" | "%" | "&" | "(" | ")" | "*" | "+" | "," |
	"-" | "."  | "/" | ":" | ";" | ">" | "=" | "<" | "?" | "@" | "[" | "\\" |
	"]" | "^" | "_" | "`" | "{" | "}" | "~" 
}
character = { letter | digit | symbol }

character1 = { character | "'" }
character2 = { character | "\"" }


eol = { NEWLINE }


line_end = { opt_whitespace ~ eol ~ line_end | opt_whitespace ~ eol }


whitespace = { " " }
opt_whitespace = { whitespace*}



// Deal with $. Can only be the first char
rule_char = { ASCII_ALPHA | ASCII_DIGIT | "_" | "$"}

rule_name = { rule_char ~ rule_name | rule_char }


