[package]
name = "ieee1800-2023-ast"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "bnf2ast2json"
path = "./src/bin/bnf2ast2json.rs"

[dependencies]
anyhow = "1.0.100"
clap = { version = "4.5.54", features = ["derive"] }
pest = { version = "2.8.5", features = ["pretty-print"] }
pest_derive = "2.8.5"
