[package]
name = "grapher"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = {version =  "4.5.54", features = ["derive"]}
iso_14977 = "0.1.0"
nom = "8.0.0"
petgraph = "0.8"
quick-xml = "0.38.4"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.148"
thiserror = "2.0.17"
ieee1800-2023-ast = { path = "../ieee1800-2023-ast"}
serde_yaml = "0.9.34"
anyhow = "1.0.100"
slab = "0.4.11"
